get:
  description: Undocumented
  security:
    - bearerAuth: []
  tags:
    - Undocumented
  responses:
    '200':
      description: get:/config response
      content:
        application/json:
          schema:
            type: object
          examples:
            response:
              externalValue: 'https://raw.githubusercontent.com/vloschiavo/powerwall2/master/samples/21.44-foogod/running/config.json'
    '401':
      $ref: '../spec.yaml#/components/responses/Unauthorized'
    '403':
      $ref: '../spec.yaml#/components/responses/Forbidden'